pipeline:
  inputs:
    path: "input_dir"

  stages:
    # Extract content from documents
    - name: extraction

    # Apply filters (optional)
    - name: length_filter
      config:
        length: 40
        comparison: "greater"
        action: "keep"

    # Generate embeddings and store locally in document metadata
    - name: qdrant_upload
      config:
        # Set mode to "local" to store embeddings in document metadata
        mode: "local"
        # Batch size for embedding generation
        batch_size: 100
        # Embedder configuration (VLLM server)
        embedder:
          url: "https://api.deepinfra.com/"
          model_name: "BAAI/bge-base-en-v1.5"
          timeout: 300
          api_key: "your-api-key-here"

    # Export documents with embeddings in metadata
    - name: export
      config:
        format: "jsonl"  # JSONL preserves metadata including embeddings
        destination: "output_with_embeddings"