pipeline:
  batch_size: 2
  inputs:
    path: "htmls" # path to the html folder
  stages:
    - name: metadata
      config:
        enabled_formats: ["pdf", "html", "txt", "md"]

    - name: export
      config: { format: "jsonl", output_dir: "output"}