pipeline:
  inputs:
    mode: "directory"
    path: "input_files"
  stages:
    - name: metadata
      config:
        enabled_formats: ["pdf", "html", "txt"]  # Extract metadata from multiple formats
        fallback_to_filename: true              # Use filename as title if extraction fails
        debug: true                             # Enable debug logging to see Scholar search progress
        export_metadata: true                   # Export metadata to JSON file
        metadata_destination: "./output"        # Directory to save metadata file
        metadata_filename: "metadata.json"      # Name of metadata JSON file
    - name: export
      config:
        format: "md"
        destination: "output/processed_files"
